# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2e41e45e5a4e416d5ed9e91c2261afbabb08407fa38bf578986b8e0281ef43fadcd033597fc5bf21d3fbc61a955745ee37851eeff21e0f1713622ee9f5d34c2

test:
  secret_key_base: 9cb162367bf73a2fae2448339554374bdfca5db5eb6838f278eb97f005d756f522f9c4203bb437a5ecd0f764ddb0e649a567ecae6319d23f1f3b73529aa735ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
